### ISSUE TITLE
Plans for luarocks?

### ISSUE THREAD

**Issue by jsmilani** [SkyLothar/lua-resty-jwt#15]
I am fairly new to Lua and coming from Ruby it is hard to live without package managers. Any chance you can add the rockspec and publish to luarocks?

Eg.
```
package = 'lua-resty-jwt'
version = '0.1.2-0'
source = {
  url = "git://github.com/SkyLothar/lua-resty-jwt",
  branch = "master"
}
description = {
  summary = 'JWT for ngx_lua and LuaJIT.',
  detailed = [[
    This library requires an nginx build 
    with OpenSSL, the ngx_lua module, 
    the LuaJIT 2.0, the lua-resty-hmac, 
    and the lua-resty-string,
  ]],
  homepage = 'https://github.com/SkyLothar/lua-resty-jwt',
  license = 'Apache License Version 2'
}
dependencies = {
  'lua >= 5.1',
  'lua-resty-hmac >= 1.0',
  'lua-resty-string >= 0.09',
}
build = {
  type = 'builtin',
  modules = {
    ['resty.jwt'] = 'lib/resty/jwt',
    ['resty.evp'] = 'lib/resty/evp'
  }
}
```

**Comment by SkyLothar** [comment]
Hmm...
I was assumed that most of the users use this lib with openresty and have no luarock installed.
Sure, I'll add this lib to luarocks.

**Comment by jsmilani** [comment]
Thank you for being accommodating.

Excuse my ignorance, but I have yet to see any best practices on how to add external libraries to openresty. There are a large number available built-in to openresty, but if you want something else then you must either use luarocks, custom makefiles/dockerfiles or manually copy the files into your own repo. I happen to be using luarocks and Dockerfiles together.

Seems to me luarocks is the "correct" lua way of installing the dependencies and it is the only option that can manage version dependencies sanely. I would agree that openresty makes it a bit difficult to use luarocks, but I found some instructions to do it. Is there some other way I have missed?

**Comment by SkyLothar** [comment]
@jsmilani Just some updates.
Really busy last few weeks,
`rockspec` was added, will publish to luarocks with next release.

You can use `luarocks make` to install latest version after cloning.

**Comment by SkyLothar** [comment]
@jsmilani 
I've published `lua-resty-jwt` on luarocks.
You can now install via `luarocks install lua-resty-jwt`
