### ISSUE TITLE
Enforcing a stricter kind of validation

### ISSUE THREAD

**Issue by fermaem** [SkyLothar/lua-resty-jwt#17]
Would you be against a stricter kind of jwt validation?

Currently when the `exp`|`nbf` claim are not expressed as a number, they're silently ignored.

Two options:

 - Make it stricter by design and fail the verification of the jwt with a meaningful message when exp isn't a number
 - Allow an optional stricter kind of validation (through `jwt:enforce_strict_validation(bool)` for instance)

**Comment by fermaem** [comment]
FWIW, I'd be happy to work on a PR to make this happening :wink:

**Comment by SkyLothar** [comment]
cool. :+1: 
by default, it's strict validation.
but you can turn it down by calling `jwt:loose_validation(true)`.

any ideas?
