### ISSUE TITLE
Question regarding expiration

### ISSUE THREAD

**Issue by junhanamaki** [SkyLothar/lua-resty-jwt#2]
Hi.

We've been playing with jwt and we've noticed that in your library, you only expire the token if "leeway" is not nil:

         if leeway ~= nil and not jwt_obj["reason"] then

Shouldn't the token be expired regardless of "leeway" being present or not, if "exp" is present in the payload of the token?

Thanks for your attention.

**Comment by SkyLothar** [comment]
thank you for your suggestion.

i've made a stupid dedication about this odd default behavior.
it's better to have 0 as default leeway when `exp` or `nbf` presents.

checkout the new 0.1.1 version~ it's fixed!

**Comment by junhanamaki** [comment]
Hi. Just wanted to say thanks for the effort and the quick fix.
