### ISSUE TITLE
Release version 0.1.3

### ISSUE THREAD

**Issue by toonetown** [SkyLothar/lua-resty-jwt#20]
Are there plans to release version 0.1.3 (which has the validation options in it), or are there other features waiting before a release happens?

**Comment by SkyLothar** [comment]
Yes, going to release 0.1.3(0.2.0?) at this weekend.
Really busy in past few days, thank you for your patient.

**Comment by toonetown** [comment]
Can I request that the releases also be gzipped - instead of just tarred?

**Comment by SkyLothar** [comment]
Sure!

**Comment by SkyLothar** [comment]
0.1.4 is released under tag v0.1.4

You can also get `.tar.gz` or `zip` format.
And you can install it via `luarocks install lua-resty-jwt`
