### ISSUE TITLE
Add support for providing a function as the key

### ISSUE THREAD

**Issue by toonetown** [SkyLothar/lua-resty-jwt#22]
It would be helpful to be able to provide a function *or* a string as the key to the verify functions.  Such a function would be passed the value of `kid` from the header as a single parameter, and would return a string to use as the key.  This would simplify, for example, using a hash table or a Redis database for looking up keys based off of the `kid` parameter.

I actually have some code that does this, and am willing to put together a pull request if it would be something that is desired.

**Comment by SkyLothar** [comment]
oh, that's a good idea.
now, i'm doing following steps to perform a `kid` validaiton

- load jwt to create a jwt_obj
- find out the right key according to the `kid`
- verify the jwt_obj

yes, a kid validation function sounds good.
much appreciated if you send a pr!

**Comment by toonetown** [comment]
OK - I'll get it worked up probably tomorrow and get something submitted for review.
