### ISSUE TITLE
Include hmac in distribution?

### ISSUE THREAD

**Issue by toonetown** [SkyLothar/lua-resty-jwt#29]
I don't know if it's possible (for licensing/other reasons), but it would be nice to include the stuff inside of "vendor/resty" in the packaged distribution when builds are made.

Again - not a super urgent issue - and it's something that can be grabbed separately, but it's kind of nice to have a distribution package that contains all the required files.

**Comment by SkyLothar** [comment]
I'm not super familiar with luarock, but 
according to [rockspec](https://github.com/SkyLothar/lua-resty-jwt/blob/master/lua-resty-jwt-dev-0.rockspec#L26), I think I already included the `hmac` lib.

So, I guess you're talking about the `.tar.gz` and `zip` in release, right?

**Comment by toonetown** [comment]
Yeah - particularly because I also do not use luarocks.  😄 I'm talking about the `.tar.gz` that you created in the release (https://github.com/SkyLothar/lua-resty-jwt/releases/download/v0.1.4/lua-resty-jwt-0.1.4.tar.gz)

Currently, I'm actually just grabbing the source and extracting just the `lib` and `vendor` paths...so it's working just fine for me.  I just thought it might be nice (for future releases) to also include `hmac.lua` in that release package.

**Comment by SkyLothar** [comment]
It's a mistake.
I put `hmac.lua` in older releases, but I forgot to put it in `0.1.4`.
Just updated the 0.1.4 release archives, `hmac.lua` included.

**Comment by toonetown** [comment]
Cool - thanks!
