### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by marcusmartins** [SkyLothar/lua-resty-jwt#3]
Hi - I was wondering what do you think about tagging the releases? It would make easier/more explicit to request a specific version when deploying/building lua-resty-jwt.

It would give you a release page within Github to easily refer to/download versions.

**Comment by SkyLothar** [comment]
cool :sunglasses:  ! thank you for your advice @marcusmartins 

release v0.1.1 is available now

and i'll add tag for feature releases.
