### ISSUE TITLE
Generating a token in php

### ISSUE THREAD

**Issue by HankBrown** [SkyLothar/lua-resty-jwt#39]
Does anyone have experience generating the token in php?

I encountered two surprises. No direct support for HS256 in php.
But if I have googled correctly, 'sha256' is the sam3 thing.

Results do not match what is generated by /sign ?

I can use curl to get a result --but that seems weird. Maybe it isn't?!

```
$payload=[
    'typ'=>"JWT",
    'alg'=>"HS256"
];
$jload = json_encode($payload);

// string hash_hmac ( string $algo , string $data , string $key [, bool $raw_output = false ] )

$key="lua-resty-jwt";

$hash = hash_hmac("sha256", $jload, $key, false);
echo "\nHASHMACF:\n$hash";

$hash = hash_hmac("sha256", $jload,$key, true);
echo "\nHASHMACT:\n$hash";

```

Appreciate any advice, thank you.
I had assumed I could generate the token in php along with the page.
But worried now I have misunderstood something essential.

**Comment by HankBrown** [comment]
http://www.sitepoint.com/php-authorization-jwt-json-web-tokens/

**Comment by HankBrown** [comment]
My problem was assuming all scripts called JWT.php were created equal.
The one I linked to above is short and sweet and _does not work_ with lua-jwt-resty.

This one is more up-to-date php-wise (name spacing etc) and **works with lua-jwt-resty.**
https://github.com/emarref/jwt

There are at least three more flavours on gitHub for php.

Neither a cutter nor a paster be. Shop carefully.

**Comment by SkyLothar** [comment]
Thanks for the heads up! 👍
