### ISSUE TITLE
Add info to the Installation section (or wiki page?) about HMAC

### ISSUE THREAD

**Issue by aarondanielson** [SkyLothar/lua-resty-jwt#43]
The HMAC library used here isn't the one available via a `luarocks install`, which installs the repo maintained here:
https://github.com/jamesmarlowe/lua-resty-hmac

The HMAC library we need instead is this one:
https://github.com/jkeys089/lua-resty-hmac

**Comment by SkyLothar** [comment]
README gives the right repo of `hmac`.
And if you use luarocks to install `lua-resty-jwt`, it automatically installs the right hmac lib. 

I'll add more tip in the readme❗ Thank for your advice

**Comment by SkyLothar** [comment]
👍  done
