### ISSUE TITLE
required key length is wrong

### ISSUE THREAD

**Issue by saks** [SkyLothar/lua-resty-jwt#44]
from [rfc](https://tools.ietf.org/html/rfc7518)

> 5.2.2.1.  AES_CBC_HMAC_SHA2 Encryption
> The number of octets in the input key K MUST be the sum of
>       MAC_KEY_LEN and ENC_KEY_LEN.  The values of these parameters are
>       specified by the Authenticated Encryption algorithms in Sections
>       5.2.3 through 5.2.5.
> 5.2.3.  AES_128_CBC_HMAC_SHA_256
>      The input key K is 32 octets long.
>      ENC_KEY_LEN is 16 octets.
>      MAC_KEY_LEN is 16 octets.
> 5.2.5.  AES_256_CBC_HMAC_SHA_512   AES_256_CBC_HMAC_SHA_512 is based on AES_128_CBC_HMAC_SHA_256, but
>   with the following differences:      The input key K is 64 octets long instead of 32.
>      ENC_KEY_LEN is 32 octets instead of 16.
>      MAC_KEY_LEN is 32 octets instead of 16.

but in code:
```lua
local function derive_keys(enc, secret_key)
  local key_size_bytes = 16
  if enc == str_const.A128CBC_HS256 then
    key_size_bytes = 16
  elseif enc == str_const.A256CBC_HS512 then
    key_size_bytes = 32
  end
  if not secret_key then
    secret_key =  resty_random.bytes(key_size_bytes,true)
  end
  if #secret_key ~= key_size_bytes then
    error({reason="The pre-shared content key must be ".. key_size_bytes})
  end
  local derived_key_size = key_size_bytes / 2
  mac_key = string_sub(secret_key, 1, derived_key_size)
  enc_key =string_sub(secret_key, derived_key_size)
  return secret_key, mac_key, enc_key
end
```

**Comment by SkyLothar** [comment]
fixed in [050627](https://github.com/SkyLothar/lua-resty-jwt/commit/050627d65bb490f274528ea554ca013d758743b5)

Thanks!

**Comment by saks** [comment]
Great! BTW, I think it would be nice to make this library compatible with other implementations (with RFC). Right now I'm working on [PR](https://github.com/SkyLothar/lua-resty-jwt/pull/45). Would be great to hear your opinion.
Thanks!

**Comment by saks** [comment]
Fixed by https://github.com/SkyLothar/lua-resty-jwt/pull/45
