### ISSUE TITLE
Standard claims (such as exp) not validated by default

### ISSUE THREAD

**Issue by jgehrcke** [SkyLothar/lua-resty-jwt#50]
This was a bummer to me. By default, the following library usage is insecure at not RFC-compliant:
```
local jwt_obj = jwt:verify(SECRET_KEY, token)
```
For example, this happily returns `jwt_obj.verified` being true, even if the token is expired.

I understand that application developers must always be responsible when using security-relevant libraries. But not validating claims by default and not explicitly warning about this in the docs in practice leads to many vulnerable applications.

`claim_spec` by default really is empty, so that `validate_claims()` by default just jumps to `return true`: https://github.com/SkyLothar/lua-resty-jwt/blob/6de92897ec6fab063d889b33baf6600df3b6f942/lib/resty/jwt.lua#L685

The JWT RFC https://tools.ietf.org/html/rfc7519 specifies the behavior of certain claims such as the `exp` claim, and I really would have assumed that `lua-resty-jwt` (like all of the other JWT libraries I have looked at) would validate those claims by default.

**What we IMO need to have, at least:** a _big big_ warning in the README that calling `local jwt_obj = jwt:verify(SECRET_KEY, token)` alone leads to a validation process that is
1) insecure (as of e.g. the missing exp validation)
2) not RFC-compliant

**What would be better:** have an example invocation in the docs that leads to RFC-compliant token verification (i.e. a verification that processes all standard claims in the way as specified in RFC 7519).

**What would be best, I think:** `jwt:verify(key, jwt_token)` should be secure/RFC-compliant. As simple as that. :)

**Comment by jgehrcke** [comment]
Note that this is a regression. Older library versions (last confirmed: 0.1.1) performed `exp` claim validation by default. This turns out to be a rather severe vulnerability, I think.

**Comment by SkyLothar** [comment]
It should validated by default, some thing must went terribly wrong. 🐞

**Comment by SkyLothar** [comment]
fixed in 0.1.8

will validate `nbf`/`exp` by default.

**Comment by jgehrcke** [comment]
Thanks for taking care of this!
