### ISSUE TITLE
Push the library on OPM ? 

### ISSUE THREAD

**Issue by tsunammis** [SkyLothar/lua-resty-jwt#55]
Hello,

Currently, I'm using your library for an another project, I would like to import it from [OPM](https://opm.openresty.org/).

Could you push your library on it please ?

I also [created a ticket](https://github.com/jkeys089/lua-resty-hmac/issues/4) on lua-resty-hmac to ask them to push their project on OPM.

Thank you.

**Comment by SkyLothar** [comment]
Of cuz, I'll push it in few days.

**Comment by tsunammis** [comment]
`lua-resty-hmac` is now on OPM under `jkeys089/lua-resty-hmac` -> https://github.com/jkeys089/lua-resty-hmac/issues/4

**Comment by tsunammis** [comment]
@SkyLothar any news ? Do you need help ?

**Comment by SkyLothar** [comment]
got really busy this week, i'll push it this weekend

**Comment by SkyLothar** [comment]
@tsunammis you can install via opm now 🎉

**Comment by tsunammis** [comment]
Great, thanks a lot !!!! 
Have a nice week-end.
