### ISSUE TITLE
luarocks install lua-resty-jwt fails

### ISSUE THREAD

**Issue by tsyrjanen** [SkyLothar/lua-resty-jwt#62]
Luarocks installation fails.

In my ubuntu desktop machine:

$sudo luarocks install lua-resty-jwt

Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/lua-resty-jwt-0.1.10-0.src.rock

Error: Couldn't extract archive .: unrecognized filename extension

And in my Dockerfile (based on CentOS):

Step 6/11 : RUN luarocks install lua-resty-jwt
 ---> Running in dd206fdf553c
Warning: falling back to curl - install luasec to get native HTTPS support

Error: Unrecognized filename extension .
Installing https://luarocks.org/lua-resty-jwt-0.1.10-0.src.rock...
Using https://luarocks.org/lua-resty-jwt-0.1.10-0.src.rock... switching to 'build' mode
The command '/bin/sh -c luarocks install lua-resty-jwt' returned a non-zero code: 1

**Comment by patricksanders** [comment]
It appears that the rockspec is broken: https://luarocks.org/manifests/skylothar/lua-resty-jwt-0.1.10-0.rockspec

The source URL is set to `'file://.'`, whereas 0.1.9 is a repo URL: https://luarocks.org/manifests/skylothar/lua-resty-jwt-0.1.9-0.rockspec

**Comment by gimbel0893** [comment]
I've been using 0.1.10-0 for about a yr with no problem.  Even rebuilt it about a week ago with no problem.

Needed to rebuild today and now having the same issue as stated above.

The manifest was changed in last ~week?  Can it be rolled back?

**Comment by patricksanders** [comment]
@gimbel0893 That seems unlikely, since 0.1.10-0 was released yesterday.

As a temporary workaround, I have pinned my version of lua-resty-jwt to `>= 0.1.8, < 0.1.10`.

**Comment by gimbel0893** [comment]
Oops thanks for correction.  I wasn't specifying version so started grabbing latest from yesterday then.  Thanks much

**Comment by SkyLothar** [comment]
😿 Sorry for the trouble.
Just released 0.1.10-1 to fix this problem.

I'll add some tests for installation check after a new version is released.

**Comment by tsyrjanen** [comment]
Thanks, it works.

$sudo luarocks install lua-resty-jwt

Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/lua-resty-jwt-0.1.10-1.src.rock
lua-resty-jwt 0.1.10-1 is now installed in /usr/local (license: Apache License Version 2)

**Comment by patricksanders** [comment]
Thanks! Works for me as well.
