### ISSUE TITLE
Enhancement:  Support for Encrypted token (JWE)

### ISSUE THREAD

**Issue by rohitjoshi** [SkyLothar/lua-resty-jwt#9]
Any plan to support for JSON Web Encryption (JWE)? 

https://tools.ietf.org/html/rfc7516

**Comment by SkyLothar** [comment]
Great idea!
I'm current stuck in another project. But I think I can make JWE supported before new year's day.
Of cause, any PR will be GREAT.

**Comment by rohitjoshi** [comment]
Thanks.  I have added support for A128CBC_HS256 and will submit a PR.

**Comment by SkyLothar** [comment]
:+1:

**Comment by rohitjoshi** [comment]
Submitted PR https://github.com/SkyLothar/lua-resty-jwt/pull/10. Let me know if any changes required.

**Comment by rohitjoshi** [comment]
PR is merged. 

https://github.com/SkyLothar/lua-resty-jwt/commit/72af76af887937eaf3758ad17f1dad1e48a64da8

Closing this issue.
